apply terraform fmt

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -10,11 +10,11 @@ jobs:
   terraform:
     name: Terraform Plan (dev)
     runs-on: ubuntu-latest
-    env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
 
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
 
     defaults:
       run:
@@ -30,17 +30,21 @@ jobs:
           terraform_version: 1.6.6
 
       - name: Terraform Init
-        run: terraform init -input=false
+        run: terraform init -input=false -no-color
 
       - name: Terraform Format Check
-        run: terraform fmt -check
+        run: terraform fmt -check -recursive
 
       - name: Terraform Validate
-        run: terraform validate
+        run: terraform validate -no-color
 
       - name: Terraform Plan
-        id: plan
         run: |
-          terraform plan -input=false -no-color -detailed-exitcode
-        continue-on-error: true
-
+          terraform plan -input=false -no-color -detailed-exitcode || \
+          if [ $? -eq 2 ]; then
+            echo "Changes detected (expected)."
+            exit 0
+          else
+            echo "Terraform failed."
+            exit 1
+          fi
